## Numpy Lerning

It is a fundamental library for scientific computing in python.


In [1]:
import numpy as np


#### Basics

In [ ]:

##### Create Arrays #####

# Create a NumPy array of numbers 1 to 10
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.arange(1,11,1) #(start,stop+1,gap)
print(arr1)

# Create a 3×3 matrix filled with random numbers
matrix = np.random.randint(1,100, size = (3,3))
print(matrix)

# Create an array of zeros and an array of ones
np.ones((3,3))
np.zeros((4,4))

[ 1  2  3  4  5  6  7  8  9 10]
[[51 74 22]
 [63 47 30]
 [73 99 96]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
##### Array Operations #####

# Square every element of an array
sqr_arr = np.square(arr)
print(sqr_arr)

# Add 2 arrays element-wise
add_arr = sqr_arr + arr
print(add_arr)

# Find min, max, and sum of an array
min = np.min(add_arr)
max= np.max(add_arr)
sum = np.sum(add_arr)
print(min,max,sum)

[  1   4   9  16  25  36  49  64  81 100]
[  2   6  12  20  30  42  56  72  90 110]
2 110 440


In [27]:
# Indexing & Slicing
# Given:
arr2 = np.array([10, 20, 30, 40, 50])

# Print the first 3 elements
print(arr2[:3])
# Print the last 2 elements
print(arr2[3:])
# Replace 20 with 200
arr2[1]=200
print(arr2)

[10 20 30]
[40 50]
[ 10 200  30  40  50]
